const projectData = [
  {
    id: 'traductora',
    name: 'Traductora',
    desc: 'A full-stack speech-to-speech translator application.',
    appURL: 'https://traductora.herokuapp.com/',
    repoURL: 'https://github.com/comatosino/Traductora',
    imgsrc: '/images/traductora-demo.gif',
    features: [
      'Harum deserunt iusto aliquid accusamus dignissimos autem',
      'Delectus velit veniam, harum debitis quam fugiat iure, magni, vitae veritatis voluptatibus asperiores alias nesciunt at!',
      'Harum deserunt iusto aliquid accusamus dignissimos autem',
    ],
    tech: ['react', 'node', 'express', 'mongodb', 'redux', 'mui'],
    challenges: [
      'Delectus velit veniam, harum debitis quam fugiat iure, magni, vitae veritatis voluptatibus asperiores alias nesciunt at!',
      'Harum deserunt iusto aliquid accusamus dignissimos autem',
      'Quia dolor aliquid eveniet aliquam, obcaecati nulla delenitiimpedit cum, quis ea distinctio.',
    ],
    successes: [
      'Delectus velit veniam, harum debitis quam fugiat iure, magni, vitae veritatis voluptatibus asperiores alias nesciunt at!',
      'Harum deserunt iusto aliquid accusamus dignissimos autem',
      'Quia dolor aliquid eveniet aliquam, obcaecati nulla delenitiimpedit cum, quis ea distinctio.',
    ],
  },
  {
    id: 'console-log',
    name: 'Console Log',
    desc: 'Create, store, and link to guides and walkthroughs for video games.',
    appURL: 'https://sar-console-log.herokuapp.com/',
    repoURL: 'https://github.com/comatosino/Console-Log',
    imgsrc: '/images/console-log-demo.gif',
    features: [
      'Delectus velit veniam, harum debitis quam fugiat iure, magni, vitae veritatis voluptatibus asperiores alias nesciunt at!',
      'Harum deserunt iusto aliquid accusamus dignissimos autem',
      'Quia dolor aliquid eveniet aliquam, obcaecati nulla delenitiimpedit cum, quis ea distinctio.',
    ],
    tech: ['react', 'node', 'express', 'mongodb', 'sequelize', 'tailwind'],
    role: [
      'Implemented voice search functionality',
      'Designed database and built RESTful API',
      'Managed GitHub repository, led code reviews, and approved pull requests',
    ],
    challenges: ['Lorem Ipsum'],
    successes: ['Ipsum Lorem'],
  },
  {
    id: 'vedomý',
    name: 'Vedomý',
    desc: 'Space for self-reflection to record thoughts and daily health habits.',
    appURL: 'https://gushihiro.github.io/Vedomy',
    repoURL: 'https://github.com/Gushihiro/Vedomy',
    imgsrc: '/images/vedomy-demo.gif',
    features: [
      'Delectus velit veniam, harum debitis quam fugiat iure, magni, vitae veritatis voluptatibus asperiores alias nesciunt at!',
      'Harum deserunt iusto aliquid accusamus dignissimos autem',
      'Quia dolor aliquid eveniet aliquam, obcaecati nulla delenitiimpedit cum, quis ea distinctio.',
    ],
    tech: ['javascript', 'html', 'css', 'materialize'],
    role: [
      'Interfaced with 3rd-Party APIs to fetch data, created and populated recipe card',
      'Led code reviews and approved pull requests',
    ],
    challenges: [
      'Delectus velit veniam, harum debitis quam fugiat iure, magni, vitae veritatis voluptatibus asperiores alias nesciunt at!',
      'Harum deserunt iusto aliquid accusamus dignissimos autem',
      'Quia dolor aliquid eveniet aliquam, obcaecati nulla delenitiimpedit cum, quis ea distinctio.',
    ],
    successes: [
      'Delectus velit veniam, harum debitis quam fugiat iure, magni, vitae veritatis voluptatibus asperiores alias nesciunt at!',
      'Harum deserunt iusto aliquid accusamus dignissimos autem',
      'Quia dolor aliquid eveniet aliquam, obcaecati nulla delenitiimpedit cum, quis ea distinctio.',
    ],
  },
  {
    id: 'pantrimonium',
    name: 'Pantrimonium',
    desc: 'Manage food inventory, monitor expiration dates, and create a shopping list.',
    appURL: 'https://pantrimonium.herokuapp.com/',
    repoURL: 'https://github.com/comatosino/Pantrimonium',
    imgsrc: '/images/pantrimonium-demo.gif',
    features: [
      'Harum deserunt iusto aliquid accusamus dignissimos autem',
      'Quia dolor aliquid eveniet aliquam, obcaecati nulla delenitiimpedit cum, quis ea distinctio.',
      'Delectus velit veniam, harum debitis quam fugiat iure, magni, vitae veritatis voluptatibus asperiores alias nesciunt at!',
    ],
    tech: ['node', 'express', 'mysql', 'bootstrap', 'handlebars'],
    role: [
      'implemented client-side CRUD functionality',
      'Built server framework and added e-mail component with Nodemailer',
      'Fulfilled project manager and GitHub repository master roles',
    ],
    challenges: [
      'Delectus velit veniam, harum debitis quam fugiat iure, magni, vitae veritatis voluptatibus asperiores alias nesciunt at!',
      'Harum deserunt iusto aliquid accusamus dignissimos autem',
      'Quia dolor aliquid eveniet aliquam, obcaecati nulla delenitiimpedit cum, quis ea distinctio.',
    ],
    successes: [
      'Delectus velit veniam, harum debitis quam fugiat iure, magni, vitae veritatis voluptatibus asperiores alias nesciunt at!',
      'Harum deserunt iusto aliquid accusamus dignissimos autem',
      'Quia dolor aliquid eveniet aliquam, obcaecati nulla delenitiimpedit cum, quis ea distinctio.',
    ],
  },
  {
    id: 'dad-jokes',
    name: 'Bearded Dad Jokes',
    desc: 'Combine the gravitas of facial hair with the dry hilarity of fatherly humor.',
    appURL: 'https://comatosino.github.io/dad-jokes/',
    repoURL: 'https://github.com/comatosino/dad-jokes',
    imgsrc: '/images/dad-jokes-demo.gif',
    features: [
      'Delectus velit veniam, harum debitis quam fugiat iure, magni, vitae veritatis voluptatibus asperiores alias nesciunt at!',
      'Quia dolor aliquid eveniet aliquam, obcaecati nulla delenitiimpedit cum, quis ea distinctio.',
      'Harum deserunt iusto aliquid accusamus dignissimos autem',
    ],
    tech: ['react', 'node', 'mui'],
    challenges: [
      'Delectus velit veniam, harum debitis quam fugiat iure, magni, vitae veritatis voluptatibus asperiores alias nesciunt at!',
      'Harum deserunt iusto aliquid accusamus dignissimos autem',
      'Quia dolor aliquid eveniet aliquam, obcaecati nulla delenitiimpedit cum, quis ea distinctio.',
    ],
    successes: [
      'Delectus velit veniam, harum debitis quam fugiat iure, magni, vitae veritatis voluptatibus asperiores alias nesciunt at!',
      'Harum deserunt iusto aliquid accusamus dignissimos autem',
      'Quia dolor aliquid eveniet aliquam, obcaecati nulla delenitiimpedit cum, quis ea distinctio.',
    ],
  },
];

export default projectData;
